export const sampleServices = [
  {
    name: 'Screen Repair & Replacement',
    description: 'Professional screen repair and replacement service for all smartphone models. We use high-quality screens with warranty. Fast service within 30-60 minutes.',
    price: 2500,
    category: 'Screen Repair',
    icon: '📱',
    featured: true,
  },
  {
    name: 'Battery Replacement',
    description: 'Original and compatible battery replacement for all brands. Includes battery health check and optimization. Get your phone running like new.',
    price: 1500,
    category: 'Battery Replacement',
    icon: '🔋',
    featured: true,
  },
  {
    name: 'Water Damage Repair',
    description: 'Expert water damage repair service. Complete device cleaning, component replacement, and restoration. Quick turnaround time.',
    price: 3000,
    category: 'Water Damage',
    icon: '💧',
    featured: false,
  },
  {
    name: 'Software Issues & Updates',
    description: 'Fix all software problems including hanging, slow performance, app crashes, and system updates. Complete software restoration available.',
    price: 800,
    category: 'Software Issues',
    icon: '💻',
    featured: true,
  },
  {
    name: 'Charging Port Repair',
    description: 'Fix charging port issues, loose connections, and charging problems. Quick diagnostic and repair service for all phone models.',
    price: 1200,
    category: 'Charging Port Repair',
    icon: '🔌',
    featured: false,
  },
  {
    name: 'Camera Repair & Replacement',
    description: 'Front and back camera repair and replacement. Fix blurry images, focus issues, and camera crashes. Original quality guaranteed.',
    price: 2000,
    category: 'Hardware Repair',
    icon: '📷',
    featured: false,
  },
  {
    name: 'Speaker & Microphone Repair',
    description: 'Professional audio repair service. Fix low volume, no sound, and microphone issues. Complete testing included.',
    price: 1000,
    category: 'Hardware Repair',
    icon: '🔊',
    featured: false,
  },
  {
    name: 'Phone Cleaning & Maintenance',
    description: 'Complete phone cleaning service including dust removal, port cleaning, and performance optimization. Keep your phone running smoothly.',
    price: 500,
    category: 'Phone Cleaning',
    icon: '✨',
    featured: false,
  },
  {
    name: 'Back Panel & Body Repair',
    description: 'Back glass replacement, body dent removal, and cosmetic repairs. Restore your phone to its original look.',
    price: 1800,
    category: 'Hardware Repair',
    icon: '🔧',
    featured: false,
  },
  {
    name: 'Button Repair & Replacement',
    description: 'Fix stuck, broken, or unresponsive buttons. Volume, power, and home button repairs for all models.',
    price: 900,
    category: 'Hardware Repair',
    icon: '🎮',
    featured: false,
  },
];

export const sampleTestimonials = [
  {
    name: 'Ahmed Khan',
    rating: 5,
    comment: 'Excellent service! My iPhone screen was replaced in just 45 minutes. Professional work and reasonable prices. Highly recommended!',
    service: 'Screen Repair',
    featured: true,
  },
  {
    name: 'Sara Ali',
    rating: 5,
    comment: 'Very satisfied with the battery replacement service. My phone battery life is now much better. Great customer service!',
    service: 'Battery Replacement',
    featured: true,
  },
  {
    name: 'Muhammad Usman',
    rating: 4,
    comment: 'Good service and honest pricing. Fixed my water damaged phone quickly. Will definitely come back for future repairs.',
    service: 'Water Damage Repair',
    featured: true,
  },
  {
    name: 'Ayesha Malik',
    rating: 5,
    comment: 'Professional and fast service. They fixed my charging port issue and now my phone charges perfectly. Thank you!',
    service: 'Charging Port Repair',
    featured: true,
  },
  {
    name: 'Hassan Raza',
    rating: 5,
    comment: 'Best mobile repair shop in the area! Fixed my software issues and phone is running smoothly now. Great experience!',
    service: 'Software Issues',
    featured: true,
  },
  {
    name: 'Fatima Sheikh',
    rating: 4,
    comment: 'Very helpful staff and quality work. Got my camera replaced and it works perfectly. Fair prices too!',
    service: 'Camera Repair',
    featured: false,
  },
  {
    name: 'Ali Haider',
    rating: 5,
    comment: 'Impressed with the service quality. Quick turnaround time and excellent customer support. Highly recommend Lashari Mobile Zone!',
    service: 'Screen Repair',
    featured: true,
  },
];
